apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  addonComponents:
#    grafana:
#      enabled: true
#      k8s:
#        replicaCount: 1
    istiocoredns:
      enabled: false
#    kiali:
#      enabled: true
#      k8s:
#        replicaCount: 1
#    prometheus:
#      enabled: true
#      k8s:
#        replicaCount: 1
#    tracing:
#      enabled: true
  components:
    base:
      enabled: true
    cni:
      enabled: false
    ingressGateways:
      - enabled: true
        k8s:
          hpaSpec:
            maxReplicas: 4
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
            minReplicas: 2
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
        name: istio-ingressgateway
    egressGateways:
      - enabled: true
        k8s:
          hpaSpec:
            maxReplicas: 4
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
            minReplicas: 2
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-egressgateway
        name: istio-egressgateway
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: "JSON"
  values:
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 8
      autoscaleMin: 3
      cpu:
        targetAverageUtilization: 80



